service: ocr-backend

provider:
  name: aws
  runtime: python3.9 # Still used as a reference
  stage: $default
  region: ap-south-1
  memorySize: 3008
  timeout: 60
  ecr:
    # This tells Serverless to build the image from the local Dockerfile
    images:
      appimage:
        path: ./

functions:
  api:
    image:
      command:
        - app.main.handler
      name: appimage
    timeout: 300
    events:
      - httpApi: '*'

# No plugins needed for Docker-based deployment
# No custom pythonRequirements needed
