service: ocr-backend

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: ap-south-1
  memorySize: 2048 # High memory for OCR tasks
  timeout: 30 # Processing documents can take time
  environment:
    # Add any environment variables here
    # PADDLE_ONEDNN_OPTERS: "0"

functions:
  api:
    handler: app.main.handler
    layers:
      - arn:aws:lambda:${aws:region}:764866452798:layer:poppler:1
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false # Disabled to avoid build errors and keep it pure Python
    zip: true # Zip dependencies to save space
    slim: true # Strips unnecessary files (test, doc, __pycache__)
    noDeploy:
      - boto3
      - botocore
      - setuptools
      - pip
